steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-backend'
    args:
      - 'build'
      - '-t'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/backend:$COMMIT_SHA'
      - '-t'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/backend:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-backend'
    waitFor: ['build-backend']
    args:
      - 'push'
      - '--all-tags'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/backend'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-backend'
    waitFor: ['push-backend']
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image=$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/backend:$COMMIT_SHA'
      - '--region=$_REGION'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--set-secrets=MONGODB_URI=MONGODB_URI:latest,JWT_SECRET=JWT_SECRET:latest,SMTP_PASS=SMTP_PASS:latest'
      - '--set-env-vars=NODE_ENV=production,SMTP_HOST=smtp.gmail.com,SMTP_PORT=587,SMTP_USER=anna@thefinu.com,CONTACT_EMAIL=anna@thefinu.com,APP_BASE_URL=https://thefinu.com'

images:
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/backend:$COMMIT_SHA'
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/backend:latest'

substitutions:
  _REGION: europe-west1
  _REPOSITORY: thefinuportal
  _SERVICE_NAME: thefinuportal-backend

options:
  logging: CLOUD_LOGGING_ONLY
